# **README**

Todo conteúdo produzido para esse notebook foi retirado e adaptado por Isaac Pereira da Conceição Araujo, do livro de Wes McKinney, Python para análise de dados. Algumas sintaxes foram revisadas com auxilio da documentação do Pandas (https://pandas.pydata.org/pandas-docs/stable/index.html) e do curso de Limpeza de dados do Kaggle (https://www.kaggle.com/learn/data-cleaning)

# **Introdução**

Durante a análise e a modelagem dos dados, um período
significativo de tempo é gasto em sua preparação: carga,
limpeza, transformação e reorganização. Sabe-se que essas
tarefas em geral ocupam 80°/o ou mais do tempo de um analista. Às vezes, o modo como os dados são armazenados em
arquivos ou em bancos de dados não constituem o formato
correto para uma tarefa em particular. 

Antes de começarmos, é interessante revisar os conteúdos sobre a linguagem Python e a biblioteca Pandas. Utilizaremos os dados **TV Shows and Movies listed on Netflix, retirado do Kaggle**.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
nfl = pd.read_csv('/content/netflix_titles.csv')
nfl.head()

  show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

# **Limpeza e preparação dos dados**

Nesta seção, discutiremos as ferramentas para dados ausentes, dados duplicados, manipulação de strings e outras
transformações de dados para análise.

## **Tratando dados ausentes**

Dados ausentes são comuns em muitas aplicações de análise de dados. Eles são representados pelo panda pelo valor ponto flutuante ***NaN*** (Not a Number). Os dados ausentes também podem ser representados por ***NA*** e ***None***.

> Podemos verificar a existência de valores nulos num dataset utilizando a função ***isnull()***. Essa função Devolve valores booleanos informando quais valores estão ausentes/são NA.

In [ ]:
# Retornando quais valores estão ausentes.
nfl.isnull()

      show_id   type  title  director  ...  rating  duration  listed_in  description
0       False  False  False      True  ...   False     False      False        False
1       False  False  False     False  ...   False     False      False        False
2       False  False  False     False  ...   False     False      False        False
3       False  False  False     False  ...   False     False      False        False
4       False  False  False     False  ...   False     False      False        False
...       ...    ...    ...       ...  ...     ...       ...        ...          ...
7782    False  False  False     False  ...   False     False      False        False
7783    False  False  False     False  ...   False     False      False        False
7784    False  False  False      True  ...   False     False      False        False
7785    False  False  False      True  ...   False     False      False        False
7786    False  False  False     False  ...   False     False      False        False

[7787 rows x 12 columns]

In [ ]:
# Verificando a quantidade total de celulas com valores NA nas primeiras 10 colunas do dataframe.
nfl.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

> Também podemos utilizar a negação do isnull, o ***notnull()***.

In [ ]:
# Retornando quais valores NÃO estão ausentes.
nfl.notnull()

      show_id  type  title  director  ...  rating  duration  listed_in  description
0        True  True   True     False  ...    True      True       True         True
1        True  True   True      True  ...    True      True       True         True
2        True  True   True      True  ...    True      True       True         True
3        True  True   True      True  ...    True      True       True         True
4        True  True   True      True  ...    True      True       True         True
...       ...   ...    ...       ...  ...     ...       ...        ...          ...
7782     True  True   True      True  ...    True      True       True         True
7783     True  True   True      True  ...    True      True       True         True
7784     True  True   True     False  ...    True      True       True         True
7785     True  True   True     False  ...    True      True       True         True
7786     True  True   True      True  ...    True      True       True         True

[7787 rows x 12 columns]

Bem, precisamos tratar os nossos valores ausentes de algum modo. O pandas nos fornece algumas alternativas para a execução desse tratamento.

> Podemos eliminar todos as linhas/colunas que possuem valores ausentes em suas celulas utilizando a função ***dropna()***. Nos seus argumentos podemos limitar sua ação a colunas específicas e/ou outras caracteristícas.

In [ ]:
# Excluindo todas as linhas que possuem valores NaN. Perceba que neste caso não sobrará nenhuma linha.
nfl.dropna()

     show_id  ...                                        description
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
5         s6  ...  A genetics professor experiments with a treatm...
...      ...  ...                                                ...
7778   s7779  ...  Looking to survive in a world taken over by zo...
7780   s7781  ...  A drug dealer starts having doubts about his t...
7781   s7782  ...  Dragged from civilian life, a former superhero...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...

[4808 rows x 12 columns]

In [ ]:
# Eliminando as linhas com valores ausentes na coluna TwoPointConv.
nfl.dropna(subset=['director'])

     show_id  ...                                        description
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
5         s6  ...  A genetics professor experiments with a treatm...
...      ...  ...                                                ...
7780   s7781  ...  A drug dealer starts having doubts about his t...
7781   s7782  ...  Dragged from civilian life, a former superhero...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7786   s7787  ...  This documentary delves into the mystique behi...

[5398 rows x 12 columns]

In [ ]:
# Eliminando todas as colunas que possuem ao menos um valor NA
nfl.dropna(axis=1)

     show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
...      ...  ...                                                ...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[7787 rows x 7 columns]

> Podemos também, preencher os dados ausentes com valores desejados utilizando a função ***fillna()***, na qual podemos aplicar alguns métodos de interpolação como ***'ffill'*** ou ***'bfill'***.

In [ ]:
# Preenchendo todos os valores nulos do dataset 
nfl.fillna("No information")

     show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
...      ...  ...                                                ...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[7787 rows x 12 columns]

In [ ]:
# Preenchendo elementos específicos sem valor em colunas específicas utilizando dict
nfl.fillna({'director': 'Director Not Informed', 'country': 'Country Not Informed'})

     show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
...      ...  ...                                                ...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[7787 rows x 12 columns]

## **Transformação de dados**

Agora partiremos para a aplciação de técnicas Filtragem, limpeza e outras transformações constituem outra classe de operações importantes

**Removendo duplicatas**

> Linhas duplicadas podem ser encontradas em um DataFrame por diversos motivos. O método ***duplicated()*** de DataFrame devolve uma Series booleana informando se cada linha é uma duplicata (foi observada em uma linha anterior) ou não:

In [ ]:
# Checando a existência de duplicatas em nosso dataset.
print(nfl.duplicated())
print("\nQuantidade de duplicatas:", nfl.duplicated().sum())

0       False
1       False
2       False
3       False
4       False
        ...
7782    False
7783    False
7784    False
7785    False
7786    False
Length: 7787, dtype: bool

Quantidade de duplicatas: 0

> No dataset que escolhemos não existem linhas duplicadas. Porém caso queiramos dropar uma possível duplicata, temos método ***drop_duplicates()***, que devolve
um DataFrame com dados em que o array duplicated é False

In [ ]:
# Criando uma dataset genérico para demonstrar o funcionamento do drop_duplicates, já que não temos duplicatas em nosso dataset
data = data= pd.DataFrame({'coluna1': ['one', 'one', 'two'] * 2,
                           'coluna2': [ 1, 1, 2, 3, 3, 4]}) 

data.head(n=len(data))

  coluna1  coluna2
0     one        1
1     one        1
2     two        2
3     one        3
4     one        3
5     two        4

In [ ]:
# Método para dropar duplicatas:
data.drop_duplicates()

  coluna1  coluna2
0     one        1
2     two        2
3     one        3
5     two        4

podemos especificar qualquer subconjunto delas na detecção de duplicatas. Suponha que tivéssemos uma coluna adicional de valores e quiséssemos filtrar as duplicatas somente com base na coluna.

In [ ]:
# Eliminando as duplicatas de uma coluna específica
data.drop_duplicates(['coluna1'])

  coluna1  coluna2
0     one        1
2     two        2

***drop_duplicates()***, por padrão, mantêm a primeira combinação de valores observados. Passar ***keep= 'last'*** devolverá a última:

In [ ]:
# Eliminando as duplicatas de uma coluna específica e deixando a ultima duplicata.
data.drop_duplicates(['coluna1'], keep='last')

  coluna1  coluna2
4     one        3
5     two        4

**Transformando dados usando uma função ou um mapeamento**

Usar a função ***map()*** é uma forma conveniente de fazer transformacões ,
em todos os elementos e executar outras operações relacionadas à limpeza de dados.

In [ ]:
nfl.head()

  show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [ ]:
# Utilizando a função map com uma função lambda para separar somente o ano que foi adicionado o filme ou série
nfl['date_added'].map(lambda x: str(x).split(',')[-1].strip())

0       2020
1       2016
2       2018
3       2017
4       2020
        ...
7782    2020
7783    2019
7784    2020
7785    2020
7786    2020
Name: date_added, Length: 7787, dtype: object

In [ ]:
# Utilizando a função map com uma função lambda para modificar as strings para torná-las maiusculas
nfl['country'].map(lambda x: str(x).upper())

0                                                  BRAZIL
1                                                  MEXICO
2                                               SINGAPORE
3                                           UNITED STATES
4                                           UNITED STATES
                              ...
7782    SWEDEN, CZECH REPUBLIC, UNITED KINGDOM, DENMAR...
7783                                                INDIA
7784                                                  NAN
7785                                            AUSTRALIA
7786                UNITED KINGDOM, CANADA, UNITED STATES
Name: country, Length: 7787, dtype: object

**Substituindo valores**

Preencher dados ausentes com o método ***fillna()*** é um caso especial da substituição mais genérica de valores. Conforme já vimos, ***map()*** pode ser usado para modificar um subconjunto de valores em um objeto, porém ***replace()*** oferece uma forma mais simples e mais flexível de fazer isso.

In [ ]:
# Utilizando o replace para traduzir o nome dos países de forma manual -- Utilizando Listas nos argumentos
nfl.replace(['Brazil', 'United States'], ['Brasil', 'Estados Unidos']).head()

  show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [ ]:
# Utilizando o replace para traduzir o nome dos países de forma manual -- Utilizando dicionários nos argumentos
nfl.replace({'Brazil':'Brasil', 'United States':'Estados Unidos'}).head()

  show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

**Renomeando os índices dos eixos**

Assim como os valores em uma Series, os rótulos dos eixos podem ser transformados de modo semelhante por uma função ou alguma forma de mapeamento, a fim de gerar objetos novos com rótulos diferentes.

In [ ]:
# Criando uma cópia de nosso dataframe e modificando o index.
nfl_copy = nfl.copy()
nfl_copy.index = nfl_copy.index.map(lambda x: f'Filme/Série {x}') 
nfl_copy.head()

              show_id  ...                                        description
Filme/Série 0      s1  ...  In a future where the elite inhabit an island ...
Filme/Série 1      s2  ...  After a devastating earthquake hits Mexico Cit...
Filme/Série 2      s3  ...  When an army recruit is found dead, his fellow...
Filme/Série 3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
Filme/Série 4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [ ]:
# Utilizando uma cópia de nosso dataframe e modificando o index e as colunas.
nfl_copy.rename(index=str.upper, columns=str.upper).head()

              show_id  ...                                        description
Filme/Série 0      s1  ...  In a future where the elite inhabit an island ...
Filme/Série 1      s2  ...  After a devastating earthquake hits Mexico Cit...
Filme/Série 2      s3  ...  When an army recruit is found dead, his fellow...
Filme/Série 3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
Filme/Série 4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

**Discretização e compartimentalização (binning)**

Dados contínuos com frequência são discretizados ou, de modo alternativo, separados em "compartimentos" (bins) para análise. O objeto devolvido pelo pandas é um objeto ***Categorical*** especial. A saída que vemos descreve os compartimentos calculados pelo pandas ***cut()*** Podemos tratá-la como um array de strings informando o nome do compartimento; internamente, ela contém um array categories que especifica os nomes distintos das categorias.

> O cut e o qcut são funções de discretização que são particularmente úteis para análise de quantis e de grupos.

In [ ]:
cut = pd.cut(nfl.release_year, bins=[1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020], labels=['Decada de 30', 'Decada de 40', 'Decada de 50', 'Decada de 60', 'Decada de 70', 'Decada de 80', 'Decada de 90', 'Decada de 2000', 'Decada de 2010']) 
cut.head()

0    Decada de 2010
1    Decada de 2010
2    Decada de 2010
3    Decada de 2000
4    Decada de 2000
Name: release_year, dtype: category
Categories (9, object): ['Decada de 30' < 'Decada de 40' < 'Decada de 50' < 'Decada de 60' < ... <
                         'Decada de 80' < 'Decada de 90' < 'Decada de 2000' < 'Decada de 2010']

**Detectando e filtrando valores discrepantes**

Filtrar ou transformar valores discrepantes (outliers) é, em
boa medida, uma questão de aplicar operações de array.

In [ ]:
nfl.describe()

       release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

**Permutação e amostragem aleatória**

Permutar (reordenar aleatoriamente) uma Series ou as linhas de um DataFrame é fácil utilizando a função numpy random permutation. Chamar permutation com o tamanho do eixo que você quer permutar gera um array de inteiros informando a nova ordem. Esse array pode então ser usado na indexação baseada em iloc ou na função take equivalente:

In [ ]:
# Criando um molde randomico para os indexes
sampler = np.random.permutation(nfl.shape[0]) 
print(sampler)

[2064 1214  979 ...   85 6190 2106]

In [ ]:
# Utilizando o molde random para permutar os indexes.
nfl.take(sampler)

     show_id  ...                                        description
2064   s2065  ...  Maverick cop Orin Boyd joins forces with an un...
1214   s1215  ...  Nestled in a faraway cloud is a rainbow-colore...
979     s980  ...  When a cop loses his vision, his detecting ski...
4796   s4797  ...  By turns scathing and candid, Patton Oswalt re...
1705   s1706  ...  Dynamic comic DeRay Davis hits the stage like ...
...      ...  ...                                                ...
3240   s3241  ...  Paul Frank's fun artwork comes to life in this...
4022   s4023  ...  In the early 1990s, the love between a cassett...
85       s86  ...  In a social experiment, a group of daughters s...
6190   s6191  ...  Three college students move into an off-campus...
2106   s2107  ...  When the McKellan family moves from Seattle to...

[7787 rows x 12 columns]

> Para selecionar um subconjunto aleatório sem substituição, o método sample le pode ser usado em Series e em DataFrame:

In [ ]:
# Permutando utilizando a função do pandas sample
nfl.sample(n=len(nfl))

     show_id  ...                                        description
2718   s2719  ...  A woman stages her own suicide but still lives...
2009   s2010  ...  While searching for her missing mother, intrep...
4945   s4946  ...  Armed with a key that allows them to morph int...
4851   s4852  ...  Struck by the lack of clean resources for mens...
7173   s7174  ...  Ricky, Julian and Bubbles bring their trailer ...
...      ...  ...                                                ...
6020   s6021  ...  Animosity gives way to love and forgiveness wh...
20       s21  ...  After accidentally connecting over the Interne...
7091   s7092  ...  Flanked by a full orchestra, Tim Minchin takes...
7387   s7388  ...  At Cross Academy, two student disciplinary com...
2559   s2560  ...  A singer and a dancer who are best friends use...

[7787 rows x 12 columns]

**Calculando variáveis indicadoras/dummy**

Outro tipo de transformação para modelagem estatística
ou aplicações de aprendizado de máquina (machine learning) consiste em converter uma variável de categorias em uma matriz "dummy" ou "indicadora". Se uma coluna em um DataFrame tiver k valores distintos, poderíamos derivar uma matriz ou um DataFrame com k colunas contendo somente 1s e Os. O pandas tem uma função ***get_dummies*** para isso, embora criar uma função por conta própria não seria difícil.

In [ ]:
# Criando uma matriz de variáveis indicadoras para a coluna type
pd.get_dummies(nfl.type)

      Movie  TV Show
0         0        1
1         1        0
2         1        0
3         1        0
4         1        0
...     ...      ...
7782      1        0
7783      1        0
7784      1        0
7785      0        1
7786      1        0

[7787 rows x 2 columns]

# **Tratamento de dados: junção, combinação e reformatação** 

Em muitas aplicações, os dados podem estar espalhados em
vários arquivos ou bancos de dados, ou podem estar organizados em um formato que não seja fácil de analisar. Estudaremos então as ferramentas que ajudam a combinar, juntar e reorganizar dados.

## **Indexação hierárquica**

A indexação hierárquica é um recurso importante do pandas;
ela permite ter vários níveis de índices (dois ou mais) em
um eixo. De forma, até certo ponto, abstrata, ela oferece
uma maneira de trabalhar com dados de dimensões mais
altas em um formato de dimensões menores.

In [ ]:
# Separando algumasa colunas do dataframe original: country, title e ano de lançamento.
nfl_country = pd.DataFrame(data={'País': np.array(nfl.country), 'Título':np.array(nfl.title), 'Ano de Lançamento':np.array(nfl.release_year)})
nfl_country.head()

            País Título  Ano de Lançamento
0         Brazil     3%               2020
1         Mexico   7:19               2016
2      Singapore  23:59               2011
3  United States      9               2009
4  United States     21               2008

In [ ]:
# Indexando um segundo nível para nosso dataset. Esse segundo nível (level=1) são oriundos de nossas colunas.
nfl_country = nfl_country.stack()
nfl_country.head(n=12)

0  País                        Brazil
   Título                          3%
   Ano de Lançamento             2020
1  País                        Mexico
   Título                        7:19
   Ano de Lançamento             2016
2  País                     Singapore
   Título                       23:59
   Ano de Lançamento             2011
3  País                 United States
   Título                           9
   Ano de Lançamento             2009
dtype: object

In [ ]:
# Retomando os níveis padrão do nosso dataset.
nfl_country.unstack()

                                                   País  ... Ano de Lançamento
0                                                Brazil  ...              2020
1                                                Mexico  ...              2016
2                                             Singapore  ...              2011
3                                         United States  ...              2009
4                                         United States  ...              2008
...                                                 ...  ...               ...
7782  Sweden, Czech Republic, United Kingdom, Denmar...  ...              2005
7783                                              India  ...              2015
7784                                                NaN  ...              2019
7785                                          Australia  ...              2019
7786              United Kingdom, Canada, United States  ...              2019

[7787 rows x 3 columns]

**Reorganizando e ordenando níveis**

Ocasionalmente precisaremos reorganizar a ordem dos níveis em um eixo ou ordenar os dados de acordo com os valores em um nível específico. O ***swap level*** aceita dois números ou nomes de níveis e devolve um novo objeto com os níveis trocados (os dados, porém, permanecem inalterados):

In [ ]:
nfl_country

0     País                                                  Brazil
      Título                                                    3%
      Ano de Lançamento                                       2020
1     País                                                  Mexico
      Título                                                  7:19
                                            ...
7785  Título                                 Zumbo's Just Desserts
      Ano de Lançamento                                       2019
7786  País                   United Kingdom, Canada, United States
      Título               ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS
      Ano de Lançamento                                       2019
Length: 22854, dtype: object

In [ ]:
# Reordenando os indexes
nfl_country.swaplevel(i=0,j=1)

País               0                                        Brazil
Título             0                                            3%
Ano de Lançamento  0                                          2020
País               1                                        Mexico
Título             1                                          7:19
                                            ...
                   7785                      Zumbo's Just Desserts
Ano de Lançamento  7785                                       2019
País               7786      United Kingdom, Canada, United States
Título             7786    ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS
Ano de Lançamento  7786                                       2019
Length: 22854, dtype: object

***sort_index***, por outro lado, ordena os dados usando os valores de um só nível. Ao trocar níveis, não é incomum usar sort_index também para que o resultado seja ordenado em ordem lexicográfica de acordo com o nível indicado

In [ ]:
# Ordenando os indexes com base no seu level
nfl_country.sort_index(level=1)

0     País                        Brazil
1     País                        Mexico
2     País                     Singapore
3     País                 United States
4     País                 United States
                               ...
7782  Ano de Lançamento             2005
7783  Ano de Lançamento             2015
7784  Ano de Lançamento             2019
7785  Ano de Lançamento             2019
7786  Ano de Lançamento             2019
Length: 22854, dtype: object

**Estatísticas de resumo por nível**

Muitas estatísticas descritivas ou de resumo em DataFrame
e em Series têm uma opção level; Com ela, podemos especificar o nível de acordo com o qual queremos fazer uma agregação, em um eixo em particular. 


Internamente, o recurso groupby do pandas foi utilizado
nesse caso;

In [ ]:
# Realizando operações de soma com os indexes agrupados
nfl_country.sum(level=1)

País                 BrazilMexicoSingaporeUnited StatesUnited State...
Título               3%7:1923:599214612218770619201922198319942,215...
Ano de Lançamento                                             15682493
dtype: object

## **Combinando e mesclando conjuntos de dados**

Os dados contidos em objetos do pandas podem ser combinados de várias maneiras: 

* ***pandas.merge*** conecta linhas em DataFrames com base em uma ou mais chaves. Essa operação será conhecida dos usuários de SQL ou de outros bancos de dados relacionais, pois ela implementa as operações de junção (join) dos bancos de dados.
* ***pandas.concat*** concatena ou "empilha" objetos ao longo de um eixo.
* O método de instância ***combine_first*** permite combinar dados que se sobrepõem a fim de preencher valores ausentes em um objeto com valores de outro objeto.

In [ ]:
# Dividindo nosso dataframe pela metade atraves das linhas
df_1_rows = nfl.iloc[:len(nfl)//2].copy()
df_2_rows = nfl.iloc[len(nfl)//2:len(nfl)].copy()

# Dividindo nosso dataframe pela metade atraves das colunas
df_1_cols = nfl.loc[:,'show_id':'country'].copy()
df_2_cols = nfl.loc[:,'date_added':].copy()

**Junções no Dataframe no estilo de bancos de dados**

O exemplo a seguir é de uma junção de muitos-para-um
(many-to-one); os dados em **df_1_rows** têm várias linhas de das colunas de nosso dataframe original, enquanto **df_2_rows** tem metade das linhas do dataframe original. Se o ***merge*** for chamado nesses objetos, teremos o
nosso dataframe original:

In [ ]:
pd.merge(df_1_rows, df_2_rows, how='outer')

     show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
...      ...  ...                                                ...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[7787 rows x 12 columns]

**Concatenando ao longo de um eixo**

Outro tipo de operação de combinação de dados é chamado,
de forma indistinta, de concatenação, vinculação (binding) ou empilhamento (stacking).

No contexto de objetos do pandas, como Series e DataFrame, ter eixos com rótulos permite generalizar melhor a concatenação de arrays. Em particular, há um número adicional de aspectos nos quais devemos pensar:
* Se os objetos estiverem indexados de modo diferente nos
outros eixos, devemos combinar os elementos distintos
nesses eixos ou usar somente os valores compartilhados
(a intersecção)?
* As porções de dados concatenadas devem ser identificáveis no objeto resultante?
* O "eixo de concatenação" contém dados que devam ser
preservados? Em muitos casos, será melhor que os rótulos inteiros default em um DataFrame sejam descartados
durante a concatenacão.

A função ***concat*** do pandas oferece uma forma consistente
de tratar cada um desses aspectos.

In [ ]:
 pd.concat([df_1_rows, df_2_rows])

     show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
...      ...  ...                                                ...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[7787 rows x 12 columns]

In [ ]:
pd.concat([df_1_cols, df_2_cols], axis=1)

     show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
...      ...  ...                                                ...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[7787 rows x 12 columns]

In [ ]:
pd.concat([df_1_cols, df_2_cols], axis=1, join='outer')

     show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
...      ...  ...                                                ...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[7787 rows x 12 columns]

**Extra: Tratando Datas**

In [ ]:
nfl.head()

  show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [ ]:
pd.to_datetime(nfl.date_added)

0      NaT
1      NaT
2      NaT
3      NaT
4      NaT
        ..
7782   NaT
7783   NaT
7784   NaT
7785   NaT
7786   NaT
Name: date_added, Length: 7787, dtype: datetime64[ns]